Description: CD12352 - Infrastructure as Code Project - Store - TrungNQ72

Parameters:
  # EnvironmentName: TrungNQ72
  EnvironmentName:
    Description: trungnq72-project02
    Type: String

Resources:
  # StaticContentBucket (#1)
  # Ref: EnvironmentName (store-params.json)
  # For Upload the project to S3: aws s3 cp s3://${EnvironmentName}-bucket-s3/index.html /var/www/html/index.html . To Lauuch Template
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-bucket-s3"
      
  # WebAppInstanceRole: #3.1
  # IAM for accessing the bucket S3 from EC2
  # Policies: s3:GetObject, s3:ListBucket
  WebAppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${EnvironmentName}-web-servers"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: s3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::${EnvironmentName}-bucket-s3/*"

  # WebAppInstanceProfile: #3.2
  # Ref WebAppInstanceRole (#3.1)
  WebAppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref WebAppInstanceRole

Outputs:
  WebAppInstanceProfileOutput:
    Description: "Return WebAppInstanceProfile"
    Value: !Ref WebAppInstanceProfile
    Export:
      Name: !Sub "TrungNQ72-Project02-WebAppInstanceProfile"
